"Argmax_get_value_of_max_items.ipynb"

Have used loops for printing the values at argmax returned indexes

**Prefer loops cause argmax can return different row indexes depending upon the dataset**

(it is not necessary that max value which be on the last row for every array in future)

In [1]:
import numpy as np

In [3]:
arr3=np.arange(20).reshape(4,5)

In [4]:
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
max=np.argmax(arr3,0)
# By specifying zero we are telling numpy to row wise in each column and return the index of row where we found the max value
# we were having 5 columns so out of each column we have the max value in the last row that is row_index=3 
max

array([3, 3, 3, 3, 3])

In [6]:
arr3.shape[1]
# It will give the number of columns in arr3

5

In [10]:
max
# this is the indexes of rows where we found the max value in each column


array([3, 3, 3, 3, 3])

In [18]:
j=0
for i in range(max.shape[0]):
    # max.shape[0] gives the number of elements in the array "max" as it is 1-D
    # Using a basic for loop which we give i=0, i=1, i=2, i=3
    if(j<=arr3.shape[1]):
        # Increase the j uptil the max numbe of columns in the arr3
        print(arr3[max[i],j])
        # print each item with row index returned by argmax and column value as resulted by j
        j+=1
        # increase value of j from 0 till (number_of_columns_in_arr3 - 1)after each execution


15
16
17
18
19
