In [2]:
import numpy as np

In [11]:
a=np.array([[3,4],[5,6]])
print(a)
b=np.array([[7,8],[1,1]])
print(b)
np.dot(a,b)

# c=np.array([[3,4],[5,6],[1,1]])
c=np.array([[3],[5],[1]])


print(c)
d=np.array([[7,8,1],[1,1,1]])
print(d)

[[3 4]
 [5 6]]
[[7 8]
 [1 1]]
[[3]
 [5]
 [1]]
[[7 8 1]
 [1 1 1]]


In [20]:
np.dot(c,d)

ValueError: shapes (3,1) and (2,3) not aligned: 1 (dim 1) != 2 (dim 0)

In [31]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
np.sum(a,axis=0)

[[1 2 3]
 [4 5 6]]


array([5, 7, 9])

In [32]:
np.sum(a,axis=1)

array([ 6, 15])

In [23]:
array1=np.array([[0.05,7.5,1.1],[1,0,0],[0,5,1]])
array2=np.array([[7,1,0],[5,0,0],[0,0.005,1]])
np.dot(array1,array2)

array([[3.785e+01, 5.550e-02, 1.100e+00],
       [7.000e+00, 1.000e+00, 0.000e+00],
       [2.500e+01, 5.000e-03, 1.000e+00]])

In [34]:
a=np.array([[1,2,3,4],[0,1,1,0]])
np.sum(a, axis=0)

array([1, 3, 4, 4])

In [35]:
np.sum(a, axis=1)

array([10,  2])