In [3]:
import numpy as np

In [10]:
arr=np.arange(1,31)
arr2=np.arange(0,16)
print(arr)
arr2

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
print(arr.reshape(5,6))
arr

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [20]:
arr3=arr.reshape(5,6)
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [37]:
a=np.arange(1,31)
b=np.arange(10,40)
print(a)
print(b)
c=a+b

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]


In [38]:
c

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69])

In [40]:
d=a-b
d

array([-9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9,
       -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9])

In [41]:
e=a*b

In [44]:
e

array([  10,   22,   36,   52,   70,   90,  112,  136,  162,  190,  220,
        252,  286,  322,  360,  400,  442,  486,  532,  580,  630,  682,
        736,  792,  850,  910,  972, 1036, 1102, 1170])

In [46]:
f=a/b
f

array([0.1       , 0.18181818, 0.25      , 0.30769231, 0.35714286,
       0.4       , 0.4375    , 0.47058824, 0.5       , 0.52631579,
       0.55      , 0.57142857, 0.59090909, 0.60869565, 0.625     ,
       0.64      , 0.65384615, 0.66666667, 0.67857143, 0.68965517,
       0.7       , 0.70967742, 0.71875   , 0.72727273, 0.73529412,
       0.74285714, 0.75      , 0.75675676, 0.76315789, 0.76923077])

In [48]:
g=a*2
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [51]:
h=a/2
h

array([ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,
        6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. ,
       11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ])

In [53]:
i=a+2
i

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [55]:
j=a>3
j

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [59]:
k=np.add(a,b)
print(k)

l=a+b
l

[11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57
 59 61 63 65 67 69]


array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69])

In [62]:
m=np.subtract(a,b)
m

array([-9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9,
       -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9])

In [64]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [70]:
n=np.arange(0,30)
o=n**0
o

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [72]:
p=a
q=np.sqrt(p)
q

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [74]:
r=a
s=np.exp(r)
s

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [78]:
t=a
u=np.log2(t)
u

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809,
       3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ,
       4.        , 4.08746284, 4.169925  , 4.24792751, 4.32192809,
       4.39231742, 4.45943162, 4.52356196, 4.5849625 , 4.64385619,
       4.70043972, 4.7548875 , 4.80735492, 4.857981  , 4.9068906 ])

In [80]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [82]:
a.max()

30

In [86]:
array_new=np.arange(0,11)
print()
array_new/0

<ipython-input-86-5cad86cd7c8b>:3: RuntimeWarning: divide by zero encountered in true_divide
  array_new/0
<ipython-input-86-5cad86cd7c8b>:3: RuntimeWarning: invalid value encountered in true_divide
  array_new/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [116]:
array_task=np.arange(1,26).reshape(5,5)
array_task

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [117]:
array_task[3:,3:]

array([[19, 20],
       [24, 25]])

In [112]:
array_trick=np.zeros(10)
array_trick+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])