In [2]:
import numpy as np

In [17]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
d=np.array([10,11,12])
np.hstack((a,b))


array([1, 2, 3, 4, 5, 6])

In [20]:
np.vstack((a,b,c,d)).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
d=np.array([1,2,1,5,4,5,7,4,1,1,2])
np.median(d)

2.0

In [25]:
np.mean(d)

3.0

In [27]:
e=np.array([1,2,1,5,4,5,7,4,1,1])

In [29]:
np.median(e)

3.0

In [31]:
np.mean(e)

3.1

In [33]:
np.std(e)

2.071231517720798

In [35]:
num1=10
num2=10
np.dot(num1,num2)

100

In [42]:
num11=[10,10]
num22=[20,20]
np.dot(num11,num22)

400

In [46]:
num111=np.array([10,10])
num222=np.array([20,20])
np.dot(num111,num222)

400

In [49]:
num1111=np.array([[10,10],[10,10]])
num2222=np.array([[20,20],[20,20]])
print(num1111)
print(num2222)
np.dot(num1111,num2222)

[[10 10]
 [10 10]]
[[20 20]
 [20 20]]


array([[400, 400],
       [400, 400]])

In [1]:
bin(11)

'0b1011'

In [2]:
~11

-12

In [3]:
~(-12)

11

In [8]:
bin(-12)

'-0b1100'