In [1]:
import scipy.integrate as integrate
import numpy as np

In [3]:
#dblquad
#integrate.dblquad(function,a ,b  ,g_func   ,h_func  )

In [5]:
help(integrate.dblquad)

Help on function dblquad in module scipy.integrate.quadpack:

dblquad(func, a, b, gfun, hfun, args=(), epsabs=1.49e-08, epsrel=1.49e-08)
    Compute a double integral.
    
    Return the double (definite) integral of ``func(y, x)`` from ``x = a..b``
    and ``y = gfun(x)..hfun(x)``.
    
    Parameters
    ----------
    func : callable
        A Python function or method of at least two variables: y must be the
        first argument and x the second argument.
    a, b : float
        The limits of integration in x: `a` < `b`
    gfun : callable or float
        The lower boundary curve in y which is a function taking a single
        floating point argument (x) and returning a floating point result
        or a float indicating a constant boundary curve.
    hfun : callable or float
        The upper boundary curve in y (same requirements as `gfun`).
    args : sequence, optional
        Extra arguments to pass to `func`.
    epsabs : float, optional
        Absolute tolerance passe

In [9]:
first=lambda x,y:16*x*y
#second
g_func=lambda x: 0
h_func=lambda y:np.sqrt(1-4*y**2)
    
integrate.dblquad(first,0,0.5,g_func,h_func)

(0.5, 1.7092350012594845e-14)

In [10]:
first=lambda x,y:16*x*y
#second
g_func=lambda y:1-2*y
h_func=lambda y:np.sqrt(1-4*y**2)
    
integrate.dblquad(first,0,0.5,g_func,h_func)

(0.33333333333333326, 1.3125184411111567e-14)

##### linalg

In [11]:
from scipy import linalg

In [15]:
A=np.array([[1,3,10],[2,12,7],[5,8,8]])
B=np.array([[10],[18],[30]])
print(A)
print(B)
X=linalg.solve(A,B)
X

[[ 1  3 10]
 [ 2 12  7]
 [ 5  8  8]]
[[10]
 [18]
 [30]]


array([[4.55393586],
       [0.51311953],
       [0.39067055]])

In [16]:
np.dot(A,X)-B

array([[0.],
       [0.],
       [0.]])

In [18]:
a=np.array([[-2,3],[4,5]])
linalg.det(a)

-22.0

In [19]:
b=linalg.inv(a)
b

array([[-0.22727273,  0.13636364],
       [ 0.18181818,  0.09090909]])

In [20]:
np.dot(a,b)

array([[1., 0.],
       [0., 1.]])